language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: DZ+iUuIXw6wBHKxWJ8cPBXlWezyDvJVEVfkv2S2SkAGJxDLuVEnQ6L1SGhdDM52VdtIwfoig9CxA6iQ4C75dFTxn2stR4Te9osq5V7CMG0wbgIXvpNYuBg9veCW9bmBKehpBTtmcr3iRNFkz1xavhg4FD2B2RK5Llxm4giqKRcPmI5WlixXUrpnVKXjSQjh+cuSUpLKbMJ46pneeCWdqpfEItyT91AVrDLzIqfSdH54nR3IfIy23LKApwlXAg1g4pGrN8nLXKErtxGbfX1LGfik063deADmjArsBSHDVeoNrCuWExCzBJ/Wr4p6jwClZjVkMf/6NeTIVolB5XFgsTDqn67U0WNrSkuZ75YQ13v6vmLzgsNet9exd4DSWhvZJEY1T9oCYGb2rxTMtEpkV47+QEwz749vxoFs3cETrAE4lm9OCsb4sZhMkhKbO4ouQCC4Ul22AZUyuPb3fu250phnmKql1EWjXgSwbMr6tOh5nkiWmw2JWC4blDBYCj4ZP4pp/zoyXPZkG7X/5MFjNobmSSv4Bs1XxqUFF8ESjp9uMFsxOJV1vDJBBjCYpcrJHctsHc57KNDeIV/twviOxNWIcwqlaJjZMS2/EW6SiF9mvku4UZmiwuTUGHDaAB0/o53CZmDWPKEHxBq9R0wkQM0NSjF2vB7AQ1PkSz5WS+tg=
  app: stark-temple-31679
  on:
    repo: pocketcalculator/node-restaurants-app-mongoose
